trigger:
- master

strategy:
  matrix:
    stable:
      rustup_toolchain: stable

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"      
    displayName: install rust
  - script: cargo build --manifest-path ./effort_visualizer/Cargo.toml
    displayName: cargo build
  - script: cargo test --manifest-path ./effort_visualizer/Cargo.toml
    displayName: cargo test

  - task: Docker@2
    displayName: 'build and push effort visualizer backend image'
    inputs:
      containerRegistry: 'dockerRegistryServiceConnection'
      repository: 'harunari/effort_visualizer'
      command: 'buildAndPush'
      Dockerfile: './effort_visualizer/Dockerfile'
      buildContext: '.'
      tags: |
        stable-$(Build.BuildId)
        stable

  - task: Docker@2
    displayName: 'build and push effort visualizer repository image'
    inputs:
      containerRegistry: 'dockerRegistryServiceConnection'
      repository: 'harunari/effort_visualizer_repository'
      command: 'buildAndPush'
      Dockerfile: './postgres/Dockerfile'
      buildContext: './postgres'
      tags: |
        stable-$(Build.BuildId)
        stable