steps:
- script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"      
  displayName: install rust
- script: cargo build --manifest-path ./effort_visualizer/Cargo.toml
  displayName: cargo build
- script: cargo test --manifest-path ./effort_visualizer/Cargo.toml
  displayName: cargo test
- script: cargo run --manifest-path ./effort_visualizer/Cargo.toml emit open-api-file > ./api-client/open-api.json
  displayName: emit open api file