steps:
- task: Bash@3
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  displayName: setup git
  inputs: 
    targetType: 'inline'
    script: |
      git config --global user.email "ryo13579978@gmail.com"
      git config --global user.name "harunari"
      if [ -n "$(git diff)" ]; then
        echo "##vso[task.setvariable variable=hasOpenApiDiff]true"
      else
        echo "##vso[task.setvariable variable=hasOpenApiDiff]false"
      fi
      git config --global url."https://${GITHUB_PAT}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

- task: NodeTool@0
  condition: and(succeeded(), eq(variables['hasOpenApiDiff'], 'true'))
  inputs:
    versionSource: 'spec'
    versionSpec: '19.x'

- task: Bash@3
  condition: and(succeeded(), eq(variables['hasOpenApiDiff'], 'true'))
  displayName: generate open api client
  inputs:
    targetType: 'inline'
    script: |
      cd ./api-client
      npm install
      npm version patch
      npx @openapitools/openapi-generator-cli generate -g typescript-fetch -i ./open-api.json
      git add ./package.json ./package-lock.json ./open-api.json
      npm publish
      git commit -m "update open api file [skip ci]" && git push origin HEAD:$(Build.SourceBranch)