steps:
- task: Docker@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  displayName: 'build and push effort visualizer backend image'
  inputs:
    containerRegistry: 'mydockerhub'
    repository: 'harunari/effort_visualizer'
    command: 'buildAndPush'
    Dockerfile: './effort_visualizer/Dockerfile'
    buildContext: '.'
    tags: |
      stable-$(Build.BuildId)
      stable